const texts = [
  "In a hamlet of ten households, there are bound to be those who are my equal in doing their best for others and in being trustworthy in what they say, but they are unlikely to be as eager to learn as I am.",
  "I stopped in the middle of that building and I saw - the sky. I saw the things that I love in this world. The work and the food and the time to sit and smoke. And I looked at the pen and I thought to myself, what the hell am I grabbing this for? Why am I trying to become what I don't want to be? What am I doing in an office, making a contemptuous, begging fool of myself, when all I want is out there, waiting for me the minute I say I know who I am!",
  "I took up my vocation, I was called by my nation. Without hesitation, my answer I gave. Now I am not wondering the things that I might have been. I'm no consolation to the forgotten brave.",
  "I didn't join a band so I could talk about my feelings. I joined it so I could hit my feelings with sticks.",
  "You must never give into despair. Allow yourself to slip down that road, and you surrender to your lowest instincts. In the darkest times, hope is something you give yourself. That is the meaning of inner strength.",
  "A zealot might be, for instance, an individual with a personal motive for revenge so overpowering that it ensures complete dedication to the cause. Or, through intensive training and psychological manipulation, an elite team of fanatic followers can be trained to sacrifice even their own lives to accomplish a given mission.",
  "There's a piece of Maria in every song that I sing. And the price of a memory is the memory of the sorrow it brings. And there is always one last light to turn out and one last bell to ring. And the last one out of the circus has to lock up everything.",
  "In 1969 four computers located around the country were in communication with each other through ARPANET. By the mid-1980s, the core of the network was in place, the communications protocols had been determined, and the Internet was live. By the early 1990s the first Internet language (http) was written and the first browser was published. The World Wide Web was born.",
  "Around midafternoon, the snow thinned into sleet, and some umbrellas appeared on Kissena Boulevard. When the green lights came on, pedestrians skirted or jumped across the puddles gathering at the curbs.",
  "Breathe, breathe in the air. Don't be afraid to care. Leave but don't leave me. Look around, choose your own ground. For long you live and high you fly. And smiles you'll give and tears you'll cry. And all you touch and all you see is all your life will ever be.",
  "I was making the most common and painful mistake women have made all throughout the ages: to naively think that with their love they can change the men they love.",
  "Have you ever thought about a world where everything is exactly the same, except you don't exist? Everything functions perfectly without you. The thought terrifies me.",
  "There's a hole in the world like a great black pit. And the vermin of the world inhabit it. And its morals aren't worth what a pig could spit. And it goes by the name of London.",
  "Radiation could be precisely determined, in principle, if we knew the reflectance of mozzarella and the cardboard in the long-wavelength regions of interest. The process is clearly governed by the Stefan-Boltzmann fourth power radiation law. Here, the oregano and other trace materials sitting on the surface might be of some importance if they changed the surface radiance in any appreciable way.",
  "The truth is... I think that we should stay, and if - and if the time comes, if the Diamonds do come to wipe this planet off the star maps, I think we should fight for this life we've built instead of tearing it up out of the ground! I think we can win. I think you can win. Earth is our home now. Isn't it worth fighting for?",
];
export default texts;
